#!/usr/bin/env node
// This tool generates a JavaScript module from a preset serialized in JSON.
// Usage: tools/build-presets [preset-name]

const child_process = require('child_process');
const path = require('path');
const fs = require('fs');
const runner = require('hygen').runner;

process.env.HYGEN_OVERWRITE = 1;

let presets;
if (process.argv.length > 2) {
  presets = process.argv.slice(2);
} else {
  presets = require('../package').presets;
}

let presetsFullInformation = [];
presets.forEach((name) => {
  const presetPath = path.join(__dirname, '../presets', name + '.json');
  const preset = require(presetPath);
  presetsFullInformation.push(preset);
})
const presetData = [];
const optionsArray = require("../src/options_array")

function getIncompatibleOptions(presetId) {
  let incompatibleOptions = []
  optionsArray.forEach((option) => {
    if(option.incompatiblePresets.includes(presetId)){
      incompatibleOptions.push(option.longId)
    }
  })
  return incompatibleOptions
}

function getPresetIsParent(presetId){
  const presetHasIdAsParent = (element) => element.inherits === presetId;
  return presetsFullInformation.some(presetHasIdAsParent)
}

presetsFullInformation.forEach(function(preset) {
  // Extract required fields from metadata
  const { id, name: presetName, description, author, knowledgeCheck, extension, complexity, timeFrame, moddedLevel, castleType, transformEarly, transformFocus, winCondition, metaExtension, metaComplexity, itemStats, listSortFlag} = preset.metadata;
  let incompatibleOptions = getIncompatibleOptions(id);
  let presetJs = `./build/presets/${id}.js`;
  let parent = getPresetIsParent(id);
  presetData.push({ name: presetName, id, description, author, knowledgeCheck, extension, complexity, timeFrame, moddedLevel, castleType, transformEarly, transformFocus, winCondition, metaExtension, metaComplexity, itemStats, listSortFlag, incompatibleOptions, presetJs, parent });

  runner(['preset', 'new', '--name', id], {
    templates: path.join(__dirname, '../templates'),
    cwd: process.cwd(),
    logger: {
      ok: console.log.bind(console),
      log: console.log.bind(console),
    },
    createPrompter: function() {},
  });
});


// Write the collected preset data to a JSON file
const outputPath = path.join(__dirname, '../preset-data.json');
fs.writeFileSync(outputPath, JSON.stringify(presetData, null, 2));
console.log('Preset data has been written to', outputPath);
