
window.BrowserConstants = window.BrowserConstants || {};

BrowserConstants.paletteSelect = elemByQuery('alucardPalette');
BrowserConstants.linerSelect = elemByQuery('alucardLiner');
BrowserConstants.paletteDisplay = elemByQuery('alucardPaletteDisplay');
BrowserConstants.linerDisplay = elemByQuery('alucardLinerDisplay');
BrowserConstants.mapColorSelect = elemByQuery('mapColor');
BrowserConstants.mapColorDisplay = elemByQuery('mapColorDisplay');

BrowserConstants.relicLocationsExtensionCache = null;

BrowserConstants.safe = sotnRando.presets.filter(function (preset) {
    return preset.id === 'safe'
}).pop()

BrowserConstants.elems = {
    output: {
        ppf: document.getElementById('output-ppf'),
        bin: document.getElementById('output-bin'),
    },
    target: document.getElementById('target'),
    status: document.getElementById('status'),
    file: document.getElementById('file'),
    form: document.getElementById('form'),
    randomize: document.getElementById('randomize'),
    seed: document.getElementById('seed'),
    preset: document.getElementById('preset'),
    presetSelect: document.getElementById('preset-select'),
    presetDetails: document.querySelector('#preset-details'),
    presetId: document.getElementById('preset-id'),
    presetDescription: document.getElementById('preset-description'),
    presetAuthor: document.getElementById('preset-author'),
    presetKnowledgeCheck: document.getElementById('preset-knowledgeCheck'),
    presetExtension: document.getElementById('preset-metaExtension'),
    presetComplexity: document.getElementById('preset-metaComplexity'),
    presetItemStats: document.getElementById('preset-itemStats'),
    presetTimeFrame: document.getElementById('preset-timeFrame'),
    presetModdedLevel: document.getElementById('preset-moddedLevel'),
    presetCastleType: document.getElementById('preset-castleType'),
    presetTransformEarly: document.getElementById('preset-transformEarly'),
    presetTransformFocus: document.getElementById('preset-transformFocus'),
    presetWinCondition: document.getElementById('preset-winCondition'),
    options: document.getElementById('options'),
    complexity: document.getElementById('complexity'),
    complexityCurrentValue: document.querySelector('#complexityCurrentValue'),
    complexityDataList: document.querySelector('#complexityValues'),
    complexityMaxValue: document.querySelector('#complexityMaxValue'),
    enemyDrops: document.getElementById('enemy-drops'),
    enemyDropsArg: document.getElementById('enemy-drops-arg'),
    startingEquipment: document.getElementById('starting-equipment'),
    startingEquipmentArg: document.getElementById('starting-equipment-arg'),
    relicLocationsSet: document.getElementById('relic-locations-set'),
    relicLocations: document.getElementById('relic-locations'),
    relicLocationsExtension: {
        guarded: document.getElementById('extension-guarded'),
        guardedplus: document.getElementById('extension-guardedplus'),
        equipment: document.getElementById('extension-equipment'),
        scenic: document.getElementById('extension-scenic'),
        extended: document.getElementById('extension-extended'),
        classic: document.getElementById('extension-classic'),
    },
    relicLocationsArg: document.getElementById('relic-locations-arg'),
    writes: document.getElementById('writes'),
    itemLocations: document.getElementById('item-locations'),
    itemLocationsArg: document.getElementById('item-locations-arg'),
    prologueRewards: document.getElementById('prologue-rewards'),
    prologueRewardsArg: document.getElementById('prologue-rewards-arg'),
    stats: document.getElementById('stats'),
    music: document.getElementById('music'),
    turkeyMode: document.getElementById('turkey-mode'),
    clear: document.getElementById('clear'),
    theme: document.getElementById('theme'),
    mapColor: document.getElementById('mapColor'),
    newGoals: document.getElementById('newGoals'),
    alucardPalette: document.getElementById('alucardPalette'),
    alucardLiner: document.getElementById('alucardLiner'),
    appendSeed: document.getElementById('append-seed'),
    tournamentMode: document.getElementById('tournament-mode'),
    colorrandoMode: document.getElementById('colorrando-mode'),
    magicmaxMode: document.getElementById('magicmax-mode'),
    antiFreezeMode: document.getElementById('antifreeze-mode'),
    mypurseMode: document.getElementById('mypurse-mode'),
    iwsMode: document.getElementById('iws-mode'),
    fastwarpMode: document.getElementById('fastwarp-mode'),
    itemNameRandoMode: document.getElementById('itemnamerando-mode'),
    noprologueMode: document.getElementById('noprologue-mode'),
    unlockedMode: document.getElementById('unlocked-mode'),
    surpriseMode: document.getElementById('surprise-mode'),
    enemyStatRandoMode: document.getElementById('enemyStatRando-mode'),
    shopPriceRandoMode: document.getElementById('shopPriceRando-mode'),
    startRoomRandoMode: document.getElementById('startRoomRando-mode'),
    startRoomRando2ndMode: document.getElementById('startRoomRando2nd-mode'),
    dominoMode: document.getElementById('domino-mode'),
    rlbcMode: document.getElementById('rlbc-mode'),
    immunityPotionMode: document.getElementById('immunity-potion-mode'),
    godspeedMode: document.getElementById('godspeed-mode'),
    libraryShortcut: document.getElementById('library-shortcut'),
    elemChaosMode: document.getElementById('elem-chaos'),
    singleHitGearMode: document.getElementById('single-hit-gear'),
    easyMode: document.getElementById('easy-mode'),
    devStashMode: document.getElementById('dev-stash'),
    seasonalPhrasesMode: document.getElementById('seasonal-phrases'),
    bossMusicSeparation: document.getElementById('boss-music-separation'),
    accessibilityPatches: document.getElementById('accessibility-patches'),
    showSpoilers: document.getElementById('show-spoilers'),
    showRelics: document.getElementById('show-relics'),
    showSolutions: document.getElementById('show-solutions'),
    spoilers: document.getElementById('spoilers'),
    spoilersContainer: document.getElementById('spoilers-container'),
    download: document.getElementById('download'),
    loader: document.getElementById('loader'),
    copy: document.getElementById('copy'),
    notification: document.getElementById('notification'),
    seedUrl: document.getElementById('seed-url'),
    showOlder: document.getElementById('show-older'),
    older: document.getElementById('older'),
    esMoveToLeft: document.getElementById('esMoveToLeft'),
    esMoveToRight: document.getElementById('esMoveToRight'),
    excludeSongsMenu: document.getElementById('excludeSongsMenu'),
    excludeSongsOption: document.getElementById('excludeSongsOption'),
    includeList: document.getElementById('includeList'),
    excludeList: document.getElementById('excludeList'),
    logo: document.getElementById('pageLogo')
}

Object.assign(window, BrowserConstants);